name: Snyk Security Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-test:
    name: Ejecutar Snyk Test
    runs-on: self-hosted

    steps:
     # - name: Checkout code
      #  uses: actions/checkout@v3

      #- name: Set up Node.js
       # uses: actions/setup-node@v3
        #with:
         # node-version: '16'

     # - name: Install dependencies
      #  run: npm install

     # - name: Install Snyk CLI
      #  run: npm install -g snyk

      - name: Imprimir mensaje en pantalla
        run: echo "¡El workflow de Snyk está funcionando correctamente!"   # Este es el paso que imprime en pantalla

      - name: Run Snyk test
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
