name: Snyk Security Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk-test:
    name: Ejecutar Snyk Test
    runs-on: self-hosted

    steps:

      - name: Imprimir mensaje en pantalla
        run: echo "¡El workflow de Snyk está funcionando correctamente!"   # Este es el paso que imprime en pantalla

      - name: Autenticar Snyk CLI
        run: snyk auth ${{secrets.SNYK_TOKEN}}

      - name: Ejecutar analisis SAST con snyk
        run: snyk code test --sarif || true > snyk-sast-report.sarif
        
      - name: Verificar si el reporte SARIF existe
        run: cat snyk-sast-report.sarif || echo "El archivo SARIF no se generó correctamente"

      - name: Subir resultados a GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with: 
          sarif_file: snyk-sast-report.sarif
